[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/next"

[build.environment]
  NODE_VERSION = "20.11.1"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
